### ISSUE TITLE
KeyError: 'sil,K,a'

### ISSUE THREAD

**Issue by VladislavBS3** [juice500ml/dysarthria-gop#1]
Hi! Trying to merge commonphone and l2-arctic I've faced the problem with l2-arctic:
```
Traceback (most recent call last):
  File "C:\Users\coolp\Documents\got_test\model\dataset.py", line 284, in <module>
    df = _prepare(args.dataset_path)
  File "C:\Users\coolp\Documents\got_test\model\dataset.py", line 250, in _prepare_l2arctic
    "phone": vocab[_remove_digits(phone)],
KeyError: 'sil,K,a'
```

As I understood "phone" refers to 'vocab' dictionary and try to get value by it's keys as [_remove_digits(phone)] in which 'sil,K,a' occurs. 
So, it takes dicision to find value by non-existing key, can't find anything and gives an error.
How can I fix it?

**Comment by juice500ml** [comment]
Hi, thank you for your interest in our paper!
L2-ARCTIC labels the textgrid labels to be `"correct_phone, wrong_phone, type_of_error"`.
https://psi.engr.tamu.edu/l2-arctic-corpus-docs/
So, I would recommend it to use the first label, i.e., `phone.split(",")[0]`.
