### ISSUE TITLE
Does this model work for predictions for small datasets?

### ISSUE THREAD

**Issue by VladislavBS3** [juice500ml/dysarthria-gop#2]
Hello! Thank you for helping with previous issue! 
I am really interested in your work and have got one more question.
I have a dataset with 50 ,wav files about 1-5 seconds. Can I predict pronounciation for each of them using model trained corresponding to the code from read.me file? And how should I do that?

**Comment by juice500ml** [comment]
Actually, you can. The model that you can train with `train_phone_recognizer.py` will yield a model that returns a stepwise phoneme prediction model.
